# Generated by Django 5.1.1 on 2024-11-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_vote_unique_together_vote_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
