# Generated by Django 5.1.1 on 2024-11-21 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
